### ISSUE TITLE
change name of app

### ISSUE THREAD

**Issue by pooja335** [eecs394-fall15/xlist#14]
they seem fairly set, they even have a logo

**Comment by kapil1garg** [comment]
Probably should do this soon...shall we ask the clients this weekend if they're set on it?

**Comment by kapil1garg** [comment]
Since everything is set and done, let's take care of this when we package the final product w/Readme

**Comment by kapil1garg** [comment]
Fixed in cde83d32d487d3a31338fa06769147695e8d3b92
